### PR TITLE
freebsd: recent changes for O_EXEC implementation

### PR DESCRIPTION
**Pull request by kevans91**
This includes a light refactoring to make sure that we're not duplicating
the check for VEXEC rights when it's already done in vfs_cache_lookup, then
honoring NOEXECCHECK if we're in a tree where it's defined.

Note that the openzfs-kmod port is still BROKEN- it needs some kind of autoconf dance to get zfs_config.h generated, and VOP_MARKATIME is now spelled VOP_MMAPPED (mjg r357361)

### CODE REVIEW

**Comment by kevans91** [comment]
I guess I should have mentioned- this is both compile-time and runtime compatible with 12.x- only the #ifdef NOEXECCHECK was needed for compatibility.

**Comment by ghost** [comment]
Thanks Kyle. Can you update the target branch of the PR to `projects/pr-rebase-20200205` please and I will merge.
I will ask someone to bump the ports once merged.

**Comment by kevans91** [comment]
Hmmm... I'll rebase this properly tomorrow- not about to try and resolve the merge conflicts via their interface.

**Comment by ghost** [comment]
I'll just cherry-pick your commit, no worries.

**Comment by ghost** [comment]
d3f3189

**Comment by kevans91** [comment]
Oh, perfect, thanks!

**Pull request closed without merging**
